version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network

  backend:
    container_name: backeend_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "3000:3000"

networks:
  app_network:
    driver: bridge
